// Offline browser smoke test. Requires Playwright and its Chromium; no robot connection.
const {chromium}=require('playwright');
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{
 let offline=false;
 const status={phase:'VISIT_CONES',armed:false,run_id:'offline-test',operation_mode:'debug',mission_profile:'a2_task_one',a2_enabled:true,motion_enabled:false,status_fresh:true,telemetry_valid:true,voltage_valid:false,depth_m:.15,cmd_depth:.1,roll_rad:0,pitch_rad:0,yaw_rad:0,surface_grid_valid:true,surface_grid_row:1.5,surface_grid_col:2.5,row:.5,col:.5,pose_valid:true,camera_age_sec:.1,frame_timeout_sec:.5,front_enabled:false,video_enabled:false,cone_count:4,cells:[{row:1,col:2,object:'circle_cone',visited:true}],planned_path:[[1,1],[1,2]],next_row:1,next_col:2,recording_enabled:true,recording_ready:true,error_flags:0};
 const server=http.createServer((req,res)=>{if(req.url==='/api/status'){res.writeHead(offline?503:200,{'Content-Type':'application/json'});res.end(JSON.stringify(status))}else if(req.url==='/api/localization'){res.end(JSON.stringify({valid:false,reason:'unverified'}))}else if(req.url==='/'){res.setHeader('Content-Type','text/html; charset=utf-8');res.end(fs.readFileSync(path.join(__dirname,'../web/index.html')))}else {res.writeHead(404);res.end()}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
 try{browser=await chromium.launch({headless:true, ...(process.env.AUV_BROWSER_CHANNEL?{channel:process.env.AUV_BROWSER_CHANNEL}:{})});const page=await browser.newPage({viewport:{width:1440,height:1080}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>document.querySelector('#connection').textContent==='已连接');assert.match(await page.locator('.cell.current').innerText(),/1,2/);assert.equal(await page.locator('#armed').innerText(),'DISARM');assert.match(await page.locator('#mode').innerText(),/DEBUG/);assert.equal(await page.locator('#front-panel').isVisible(),false);assert.match(await page.locator('#route').innerText(),/1,1 → 1,2/);
 await page.selectOption('#preview','hls');assert.match(await page.locator('#video-state').innerText(),/未启用/);
 if(process.env.AUV_DASHBOARD_SCREENSHOT)await page.screenshot({path:process.env.AUV_DASHBOARD_SCREENSHOT,fullPage:true});
 offline=true;await page.waitForFunction(()=>document.querySelector('#connection').textContent==='连接中断');assert.match(await page.locator('#armed').innerText(),/未知/);assert.equal(await page.locator('body').evaluate(e=>e.classList.contains('stale')),true);
 const downloadPromise=page.waitForEvent('download');await page.click('#export');const download=await downloadPromise;const stream=await download.createReadStream();let data='';for await(const chunk of stream)data+=chunk;const exported=JSON.parse(data);assert.equal(exported.status.run_id,'offline-test');assert.ok(exported.last_received_at);assert.equal(exported.stale,true);
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(errors,[]);console.log('PASS: A2 position, DISARM, cameras, HLS, disconnect, export and mobile layout');
 }finally{if(browser)await browser.close();await new Promise(r=>server.close(r))}
})().catch(e=>{console.error(e);process.exitCode=1});
