'use strict';
let records=[],errors=[];
const $=id=>document.getElementById(id);
function unwrap(r){return r.observation?.status||r.observation?.telemetry||r.telemetry||r.imu||r}
function time(r){return r.pc_monotonic_s??r.steady_sec??r.monotonic??r.stamp??null}
function fault(r){return !!(r.error||r.fault||unwrap(r).fault||r.changes?.length||/FAULT|ERROR/i.test(r.event||r.phase||''))}
function summary(){const sources=[...new Set(records.map(x=>x._file))];return {schema:'deepblue.ai_analysis.v1',purpose:'Observed evidence, not a diagnosis or motion authorization',records:records.length,files:sources,parse_errors:errors,flagged_records:records.filter(fault).length,limitations:['Sampling can miss transitions','PC and Pi monotonic clocks differ','Repeated camera telemetry is not independent sensor data','Null and missing values are unknown','No automatic cause inference'],clock_groups:[...new Set(records.map(r=>r.session_id||r.run_id||r._file))]}}
function render(){const s=summary();$('summary').textContent=`记录 ${s.records} 条 · 文件 ${s.files.length} 个 · 故障/变化 ${s.flagged_records} 条 · 解析错误 ${s.parse_errors.length} 条\n\n来源：${s.files.join('、')||'无'}\n\n注意：采样可能遗漏短暂变化；不同设备时钟不可直接相减；缺失值保持未知。\n${s.parse_errors.map(e=>e.file+':'+e.line+' '+e.error).join('\n')}`;$('rows').replaceChildren();const q=$('search').value.toLowerCase();for(const r of records.filter(r=>(!$('faults').checked||fault(r))&&JSON.stringify(r).toLowerCase().includes(q)).slice(-300)){const tr=document.createElement('tr');for(const value of [r._file+'\n'+(r.utc||r.received_utc||(r.timestamp_unix_ms!=null?new Date(r.timestamp_unix_ms).toISOString():time(r)??'时间未知')),r.event||r.phase||r.record_type||'观测']){const td=document.createElement('td');td.textContent=value;tr.append(td)}const td=document.createElement('td'),d=document.createElement('details'),h=document.createElement('summary'),p=document.createElement('pre');h.textContent=(fault(r)?'⚠ ':'')+(r.error||r.fault||r.reason||r.detail||'查看原始字段');p.textContent=JSON.stringify(r,null,2);d.append(h,p);td.append(d);tr.append(td);$('rows').append(tr)}plot();$('status').textContent=`已读取 ${records.length} 条，解析错误 ${errors.length} 条。`}
function plot(){const c=$('chart'),x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);const groups=new Map();for(const r of records){const key=(r.session_id||r.run_id||r._file)+'|'+(r.pc_monotonic_s!=null?'pc':'source');if(!groups.has(key))groups.set(key,[]);groups.get(key).push(r)}let i=0;for(const rows of groups.values()){const points=rows.map(r=>{const t=unwrap(r);return {t:time(r),d:r.imu_valid===false||t.depth_sample_fresh===false?null:t.depth_m}}).filter(p=>Number.isFinite(p.t)).sort((a,b)=>a.t-b.t);const valid=points.filter(p=>Number.isFinite(p.d));if(!valid.length)continue;const min=valid.reduce((n,p)=>Math.min(n,p.d),Infinity),max=valid.reduce((n,p)=>Math.max(n,p.d),-Infinity),a=points[0].t,b=points.at(-1).t;x.strokeStyle=['#68b9ec','#f1c675','#69d0b8'][i++%3];x.beginPath();let start=false;for(const p of points){if(!Number.isFinite(p.d)){start=false;continue}const px=50+(p.t-a)/Math.max(b-a,.001)*1000,py=30+(p.d-min)/Math.max(max-min,.05)*170;if(start)x.lineTo(px,py);else x.moveTo(px,py);start=true}x.stroke();x.fillStyle=x.strokeStyle;x.fillText(`${min.toFixed(3)}–${max.toFixed(3)} m · ${valid.length} observations`,55,225-(i-1)*15)}}
$('files').onchange=async()=>{records=[];errors=[];const files=[...$('files').files];if(files.reduce((n,f)=>n+f.size,0)>20*1024*1024){$('status').textContent='文件总量超过 20 MB，请分批导入';return}for(const f of files){const text=(await f.text()).replace(/^\uFEFF/,'');const lines=f.name.endsWith('.json')?[text]:text.split(/\r?\n/);for(const [i,line]of lines.entries()){if(!line.trim())continue;try{const r=JSON.parse(line);if(!r||Array.isArray(r)||typeof r!=='object')throw Error('Expected object');if(records.length>=100000)throw Error('record limit');records.push({...r,_file:f.name,_line:i+1})}catch(e){if(errors.length<100)errors.push({file:f.name,line:i+1,error:e.message})}}}render()};
$('live').onclick=async()=>{try{const r=await fetch('/logs',{signal:AbortSignal.timeout(2000)});if(!r.ok)throw Error('当前入口无 ROV 日志 API，请导入文件');const s=await r.json();records=(s.recent||[]).map(r=>({...r,_file:s.directory}));errors=[];render()}catch(e){$('status').textContent=e.message}};
$('search').oninput=render;$('faults').onchange=render;$('export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({summary:summary(),records},null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='deepblue-ai-log.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
